version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  # Map container port 27017 to host port 27017
    volumes:
      - ./mongodb_data:/data/db  # Mount a volume for MongoDB data persistence
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Optional: Set the root username
      MONGO_INITDB_ROOT_PASSWORD: admin  # Optional: Set the root password
