services:
	redis:
		image: redis:alpine
		container_name: redis
		restart: always
		command: redis-server --requirepass ${REDIS_PASSWORD}
		ports:
			- 6380:6379
		volumes:
			- ./data:/data
		networks:
			- redis
		logging:
		  driver: "json-file"
			options:
			  max-size: "5m" # maximum log file size.
				max-file: "5" # maximum number of log files.

networks:
  redis:
    driver: bridge
