version: "3.8"

services:

	redis:
		image: redis:alpine
		container_name: redis
		restart: always
		ports:
			- 6380:6379
		volumes:
			- ./data:/data
		environment:
			- REDIS_PASSWORD=<password>
			- REDIS_REPLICATION_MODE=master
			- REDIS_REPLICATION_MASTER_AUTH=<password>
			- REDIS_REPLICATION_MASTER_USER=<username>
			- REDIS_REPLICATION_MASTER_PASSWORD=<password>
			- REDIS_REPLICATION_MASTER_USE_TLS=yes
